"""create resumes table

Revision ID: 6c5b8ff53a21
Revises: 506bc143b70b
Create Date: 2026-10-02 18:52:13.538938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c5b8ff53a21'
down_revision: Union[str, None] = '506bc143b70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###