"""add is_expired to jobs

Revision ID: cac26d6a8e02
Revises: eaa13fcf7a3a
Create Date: 2026-10-05 07:51:52.700791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cac26d6a8e02'
down_revision: Union[str, None] = 'eaa13fcf7a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_expired', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_expired')
    # ### end Alembic commands ###