"""create profiles table

Revision ID: e01819fca63a
Revises: 73bf4c95e33b
Create Date: 2026-10-02 18:30:22.205002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e01819fca63a'
down_revision: Union[str, None] = '73bf4c95e33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('remote_preference', sa.String(length=32), nullable=True),
    sa.Column('preferred_employment_types', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('work_authorization', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###