"""create deadlines table

Revision ID: eaa13fcf7a3a
Revises: 79e417a7a40f
Create Date: 2026-10-05 07:41:15.614532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eaa13fcf7a3a'
down_revision: Union[str, None] = '79e417a7a40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_application_id'), 'deadlines', ['application_id'], unique=False)
    op.create_index(op.f('ix_deadlines_due_at'), 'deadlines', ['due_at'], unique=False)
    op.create_index(op.f('ix_deadlines_user_id'), 'deadlines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deadlines_user_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_due_at'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_application_id'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###